### ISSUE TITLE
SVG not converted correctly

### ISSUE THREAD

**Issue by arberg** [trello/victor#54]
I have a file exported from Sketch which does not convert correctly by victor. Any clue as to what is wrong? Is it a bad svg or is it victor that is not fully compatible?

I have opened the file in chrome and internet explorer and there the SVG looks fine.

Png's and SVG at:
https://spaces.hightail.com/space/av9Ic

**Comment by dlew** [comment]
Unfortunately, this is a limitation of our Batik dependency (which is what is used for actually converting SVG -> PNG). It doesn't handle `url()` tags well.

This was discussed more in #42.

**Comment by arberg** [comment]
Thank you very much for your kind help. Now, at least I know where to look if I want to fix it. And it is especially helpful to know how to determine whether it will fail handling an SVG. I think it would be helpful with at small note in the documentation.

I have created a Batik bug report here: https://issues.apache.org/jira/browse/BATIK-1156 
It would be beneficial if you could review my batik bug-report, to see if it is correct based on what Victor uses. I can see Victor uses Batik 1.8 so that is where I created the issue.

I have updated the known issues and created a pull-request: https://github.com/trello/victor/pull/55

**Comment by arberg** [comment]
FYI: This bug is now in the process of being fixed in BATIK.  It should be fixed but not yet released I think

https://issues.apache.org/jira/browse/BATIK-1170
https://issues.apache.org/jira/browse/BATIK-1156

**Comment by dlew** [comment]
Excellent! I'm going reopen this issue and we can close it when we get a new version of Batik.

**Comment by arberg** [comment]
I suspect this site tells me there's a new batik version 1.9. 

https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-util

The bug was in version 1.8.

**Comment by dlew** [comment]
Hmm... when upgrading to Batik 1.9, it renders correctly on my machine. But when I send it to Travis CI, it does not render correctly. It looks like it doesn't solve this on 100% of Java versions, in other words.

I might still merge it since hey, it's good that it's working on more versions now. What do you think?

**Comment by arberg** [comment]
If its a never Batik version that's not already known to be worse, then I would merge the new. 

I can see you have created a upgrade-batik branch. I tried it but I cannot figure out how to include it as a subproject in my gradle script and run the plugin. I tried the sample project, but it seems to use the maven version. I have attached the svg's which I have that failed in conversion.

Best Alex

[svgFailConversion.zip](https://github.com/trello/victor/files/1159205/svgFailConversion.zip)

**Comment by dlew** [comment]
Alright, I'm going to do a merge without the test then. Having the option (if running on a newer JVM) is better than no option at all.

**Comment by arberg** [comment]
Sadly issue is still in victor 1.0.0 using batik-1.9. I have reported this on the batik bug-tracker. Thanks for the effort though.

**Comment by arberg** [comment]
FYI: I have now created a new Batik issue, in case the Batik-developers are interested in fixing the problem: https://issues.apache.org/jira/browse/BATIK-1201. They closed the old issue, hence the new issue.

**Comment by bnrdk** [comment]
I've just tested Batik trunk and Batik 1.9 build as mentioned in comment here https://issues.apache.org/jira/browse/BATIK-1201, and I'm happy to report that it works in the trunk (but not in 1.9 as we see in trello).

**Comment by dlew** [comment]
I'm gonna reopen this until we get this merged in.

Thanks for the updates everyone!
